export const queries = {
    
    // usuarios
    getUsuarios: 'SELECT * FROM USUARIO', 


    // items
    getItems: 'SELECT ITEM_DETALLE.ITEM_DETALLE_ID, ITEM_DETALLE.ITEM_DETALLE_SUCURSAL_ID, ITEM_DETALLE.ITEM_DETALLE_ITEM_ID, ITEM.ITEM_DESCRIPCION, ITEM.ITEM_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_STOCK_MINIMO, ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID, UNIDAD.UNIDAD_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_MARCA, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_UNO, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_DOS, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_TRES, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_CUATRO, ITEM_DETALLE.ITEM_DETALLE_STATUS, ITEM_DETALLE.ITEM_DETALLE_FECHA_FABRICACION, ITEM_DETALLE.ITEM_DETALLE_FECHA_VENCIMIENTO, ITEM_DETALLE.ITEM_DETALLE_OBSERVACION FROM ITEM_DETALLE LEFT OUTER JOIN ITEM ON ITEM_DETALLE.ITEM_DETALLE_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON ITEM.ITEM_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID LEFT OUTER JOIN UNIDAD ON ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID = UNIDAD.UNIDAD_ID', 

    getItemsRubroId: 'SELECT ITEM_DETALLE.ITEM_DETALLE_ID, ITEM_DETALLE.ITEM_DETALLE_SUCURSAL_ID, ITEM_DETALLE.ITEM_DETALLE_ITEM_ID, ITEM.ITEM_DESCRIPCION, ITEM.ITEM_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_STOCK_MINIMO, ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID, UNIDAD.UNIDAD_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_MARCA, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_UNO, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_DOS, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_TRES, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_CUATRO, ITEM_DETALLE.ITEM_DETALLE_STATUS, ITEM_DETALLE.ITEM_DETALLE_FECHA_FABRICACION, ITEM_DETALLE.ITEM_DETALLE_FECHA_VENCIMIENTO, ITEM_DETALLE.ITEM_DETALLE_OBSERVACION FROM ITEM_DETALLE LEFT OUTER JOIN ITEM ON ITEM_DETALLE.ITEM_DETALLE_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON ITEM.ITEM_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID LEFT OUTER JOIN UNIDAD ON ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID = UNIDAD.UNIDAD_ID WHERE ITEM.ITEM_RUBRO_ID = @id', 

    getItemsCategoriaId: 'SELECT ITEM_DETALLE.ITEM_DETALLE_ID, ITEM_DETALLE.ITEM_DETALLE_SUCURSAL_ID, ITEM_DETALLE.ITEM_DETALLE_ITEM_ID, ITEM.ITEM_DESCRIPCION, ITEM.ITEM_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_STOCK_MINIMO, ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID, UNIDAD.UNIDAD_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_MARCA, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_UNO, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_DOS, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_TRES, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_CUATRO, ITEM_DETALLE.ITEM_DETALLE_STATUS, ITEM_DETALLE.ITEM_DETALLE_FECHA_FABRICACION, ITEM_DETALLE.ITEM_DETALLE_FECHA_VENCIMIENTO, ITEM_DETALLE.ITEM_DETALLE_OBSERVACION FROM ITEM_DETALLE LEFT OUTER JOIN ITEM ON ITEM_DETALLE.ITEM_DETALLE_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON ITEM.ITEM_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID LEFT OUTER JOIN UNIDAD ON ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID = UNIDAD.UNIDAD_ID WHERE ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = @id', 


    // rubros
    getRubros: 'SELECT RUBRO_ID, RUBRO_DESCRIPCION, RUBRO_ICONO FROM RUBRO', 


    // categorias
    getCategorias: 'SELECT CATEGORIA_ID, CATEGORIA_DESCRIPCION, CATEGORIA_RUBRO_ID, CATEGORIA_ICONO FROM CATEGORIA', 

    getCategoriasRubroId: 'SELECT CATEGORIA_ID, CATEGORIA_DESCRIPCION, CATEGORIA_RUBRO_ID, CATEGORIA_ICONO FROM CATEGORIA WHERE CATEGORIA_RUBRO_ID = @id', 

    getCiudades: 'SELECT CIUDAD_ID, CIUDAD_DESCRIPCION, CIUDAD_PROVINCIA_ID, PROVINCIA.PROVINCIA_DESCRIPCION, CIUDAD_PROPIEDADES, CIUDAD_IMAGEN FROM CIUDAD LEFT OUTER JOIN PROVINCIA ON CIUDAD.CIUDAD_PROVINCIA_ID = PROVINCIA.PROVINCIA_ID', 
    
    getCiudadesProvinciaId: 'SELECT CIUDAD_ID, CIUDAD_DESCRIPCION, CIUDAD_PROVINCIA_ID, PROVINCIA.PROVINCIA_DESCRIPCION, CIUDAD_PROPIEDADES, CIUDAD_IMAGEN FROM CIUDAD LEFT OUTER JOIN PROVINCIA ON CIUDAD.CIUDAD_PROVINCIA_ID = PROVINCIA.PROVINCIA_ID WHERE CIUDAD_PROVINCIA_ID = @id', 

    getProvincias: 'SELECT PROVINCIA_ID, PROVINCIA_DESCRIPCION FROM PROVINCIA', 

    newInmueble: `INSERT INTO INMUEBLE (INMUEBLE_DESCRIPCION, INMUEBLE_DIRECCION, INMUEBLE_CIUDAD_ID, INMUEBLE_HOMOLOGADO, INMUEBLE_NUMERO_HABILITACION, INMUEBLE_TIPO_INMUEBLE_ID, INMUEBLE_STATUS, INMUEBLE_SERVICIO_ID, INMUEBLE_CATEGORIA, INMUEBLE_HABITACIONES, INMUEBLE_PLANTAS, INMUEBLE_CAMAS_DOBLES, INMUEBLE_CAMAS_SIMPLES, INMUEBLE_ROPA_BLANCA, INMUEBLE_TOALLAS, INMUEBLE_ADULTOS, INMUEBLE_NINIOS, INMUEBLE_COCINA, INMUEBLE_TIPO_PENSION_ID, INMUEBLE_MICROHONDAS, INMUEBLE_CAFETERA, INMUEBLE_REFRIGERADOR, INMUEBLE_LAVARROPA, INMUEBLE_CAJA_FUERTE, INMUEBLE_BANIOS, INMUEBLE_COCHERA, INMUEBLE_COCHERA_AUTOS, INMUEBLE_PILETA, INMUEBLE_GIMNASIO, INMUEBLE_SPA, INMUEBLE_PARQUE_JUEGOS, INMUEBLE_MASCOTA, INMUEBLE_WIFI, INMUEBLE_TV, INMUEBLE_ALARMA, INMUEBLE_CALEFACCION, INMUEBLE_AIRE_ACONDICIONADO, INMUEBLE_CANCELACION_GRATIS, INMUEBLE_RESERVA_SIN_TARJETA, INMUEBLE_PAGO_ADELANTADO, INMUEBLE_IMAGEN_UNO, INMUEBLE_IMAGEN_DOS, INMUEBLE_IMAGEN_TRES, INMUEBLE_IMAGEN_CUATRO, INMUEBLE_IMAGEN_CINCO, INMUEBLE_USUARIO_ID)
    VALUES (@inmueble_descripcion, @inmueble_direccion, @inmueble_ciudad_id, @inmueble_homologado, @inmueble_numero_habilitacion, @inmueble_tipo_inmueble_id, @inmueble_status, @inmueble_servicio_id, @inmueble_categoria, @inmueble_habitaciones, @inmueble_plantas, @inmueble_camas_dobles, @inmueble_camas_simples, @inmueble_ropa_blanca, @inmueble_toallas, @inmueble_adultos, @inmueble_ninios, @inmueble_cocina, @inmueble_tipo_pension_id, @inmueble_microhondas, @inmueble_cafetera, @inmueble_refrigerador, @inmueble_lavarropa, @inmueble_caja_fuerte, @inmueble_banios, @inmueble_cochera, @inmueble_cochera_autos, @inmueble_pileta, @inmueble_gimnasio, @inmueble_spa, @inmueble_parque_juegos, @inmueble_mascota, @inmueble_wifi, @inmueble_tv, @inmueble_alarma, @inmueble_calefaccion, @inmueble_aire_acondicionado, @inmueble_cancelacion_gratis, @inmueble_reserva_tarjeta, @inmueble_pago_adelantado, @inmueble_imagen_uno, @inmueble_imagen_dos, @inmueble_imagen_tres, @inmueble_imagen_cuatro, @inmueble_imagen_cinco, @inmueble_usuario_id)`, 

    getInmuebles: 'SELECT * FROM INMUEBLE', 

    getInmueblePensiones: 'SELECT INMUEBLE_PENSION_ID, INMUEBLE_PENSION_DESCRIPCION FROM INMUEBLE_PENSION', 

    getInmuebleServicios: 'SELECT INMUEBLE_SERVICIO_ID, INMUEBLE_SERVICIO_DESCRIPCION FROM INMUEBLE_SERVICIO', 

    getInmuebleTipos: 'SELECT INMUEBLE_TIPO_ID, INMUEBLE_TIPO_DESCRIPCION FROM INMUEBLE_TIPO', 

}