export const queries = {
    
    // usuarios
    getUsuarios: 'SELECT * FROM USUARIO', 


    // items
    getItems: 'SELECT ITEM_DETALLE.ITEM_DETALLE_ID, ITEM_DETALLE.ITEM_DETALLE_SUCURSAL_ID, ITEM_DETALLE.ITEM_DETALLE_ITEM_ID, ITEM.ITEM_DESCRIPCION, ITEM.ITEM_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_STOCK_MINIMO, ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID, UNIDAD.UNIDAD_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_MARCA, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_UNO, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_DOS, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_TRES, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_CUATRO, ITEM_DETALLE.ITEM_DETALLE_STATUS, ITEM_DETALLE.ITEM_DETALLE_FECHA_FABRICACION, ITEM_DETALLE.ITEM_DETALLE_FECHA_VENCIMIENTO, ITEM_DETALLE.ITEM_DETALLE_OBSERVACION FROM ITEM_DETALLE LEFT OUTER JOIN ITEM ON ITEM_DETALLE.ITEM_DETALLE_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON ITEM.ITEM_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID LEFT OUTER JOIN UNIDAD ON ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID = UNIDAD.UNIDAD_ID', 

    getItemsRubroId: 'SELECT ITEM_DETALLE.ITEM_DETALLE_ID, ITEM_DETALLE.ITEM_DETALLE_SUCURSAL_ID, ITEM_DETALLE.ITEM_DETALLE_ITEM_ID, ITEM.ITEM_DESCRIPCION, ITEM.ITEM_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_STOCK_MINIMO, ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID, UNIDAD.UNIDAD_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_MARCA, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_UNO, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_DOS, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_TRES, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_CUATRO, ITEM_DETALLE.ITEM_DETALLE_STATUS, ITEM_DETALLE.ITEM_DETALLE_FECHA_FABRICACION, ITEM_DETALLE.ITEM_DETALLE_FECHA_VENCIMIENTO, ITEM_DETALLE.ITEM_DETALLE_OBSERVACION FROM ITEM_DETALLE LEFT OUTER JOIN ITEM ON ITEM_DETALLE.ITEM_DETALLE_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON ITEM.ITEM_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID LEFT OUTER JOIN UNIDAD ON ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID = UNIDAD.UNIDAD_ID WHERE ITEM.ITEM_RUBRO_ID = @id', 

    getItemsCategoriaId: 'SELECT ITEM_DETALLE.ITEM_DETALLE_ID, ITEM_DETALLE.ITEM_DETALLE_SUCURSAL_ID, ITEM_DETALLE.ITEM_DETALLE_ITEM_ID, ITEM.ITEM_DESCRIPCION, ITEM.ITEM_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_STOCK_MINIMO, ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID, UNIDAD.UNIDAD_DESCRIPCION, ITEM_DETALLE.ITEM_DETALLE_MARCA, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_UNO, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_DOS, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_TRES, ITEM_DETALLE.ITEM_DETALLE_IMAGEN_CUATRO, ITEM_DETALLE.ITEM_DETALLE_STATUS, ITEM_DETALLE.ITEM_DETALLE_FECHA_FABRICACION, ITEM_DETALLE.ITEM_DETALLE_FECHA_VENCIMIENTO, ITEM_DETALLE.ITEM_DETALLE_OBSERVACION FROM ITEM_DETALLE LEFT OUTER JOIN ITEM ON ITEM_DETALLE.ITEM_DETALLE_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON ITEM.ITEM_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID LEFT OUTER JOIN UNIDAD ON ITEM_DETALLE.ITEM_DETALLE_UNIDAD_ID = UNIDAD.UNIDAD_ID WHERE ITEM_DETALLE.ITEM_DETALLE_CATEGORIA_ID = @id', 


    // rubros
    getRubros: 'SELECT RUBRO_ID, RUBRO_DESCRIPCION, RUBRO_ICONO FROM RUBRO', 


    // categorias
    getCategorias: 'SELECT CATEGORIA_ID, CATEGORIA_DESCRIPCION, CATEGORIA_RUBRO_ID, CATEGORIA_ICONO FROM CATEGORIA', 

    getCategoriasRubroId: 'SELECT CATEGORIA_ID, CATEGORIA_DESCRIPCION, CATEGORIA_RUBRO_ID, CATEGORIA_ICONO FROM CATEGORIA WHERE CATEGORIA_RUBRO_ID = @id', 

    getCiudades: 'SELECT CIUDAD_ID, CIUDAD_DESCRIPCION, CIUDAD_PROVINCIA_ID, PROVINCIA.PROVINCIA_DESCRIPCION, CIUDAD_PROPIEDADES, CIUDAD_IMAGEN FROM CIUDAD LEFT OUTER JOIN PROVINCIA ON CIUDAD.CIUDAD_PROVINCIA_ID = PROVINCIA.PROVINCIA_ID', 
    
    getCiudadesProvinciaId: 'SELECT CIUDAD_ID, CIUDAD_DESCRIPCION, CIUDAD_PROVINCIA_ID, PROVINCIA.PROVINCIA_DESCRIPCION, CIUDAD_PROPIEDADES, CIUDAD_IMAGEN FROM CIUDAD LEFT OUTER JOIN PROVINCIA ON CIUDAD.CIUDAD_PROVINCIA_ID = PROVINCIA.PROVINCIA_ID WHERE CIUDAD_PROVINCIA_ID = @id', 

    getProvincias: 'SELECT PROVINCIA_ID, PROVINCIA_DESCRIPCION FROM PROVINCIA', 

    newInmueble: ``, 

    getInmuebles: 'SELECT * FROM INMUEBLE', 

    getInmueblePensiones: 'SELECT INMUEBLE_PENSION_ID, INMUEBLE_PENSION_DESCRIPCION FROM INMUEBLE_PENSION', 

    getInmuebleServicios: 'SELECT INMUEBLE_SERVICIO_ID, INMUEBLE_SERVICIO_DESCRIPCION FROM INMUEBLE_SERVICIO', 

    getInmuebleTipos: 'SELECT INMUEBLE_TIPO_ID, INMUEBLE_TIPO_DESCRIPCION FROM INMUEBLE_TIPO', 

    getOfertas: 'SELECT OFERTA_ID, OFERTA_FECHA, OFERTA_EMPAQUE_ID, EMPAQUE.EMPAQUE_DESCRIPCION, OFERTA_DESCRIPCION, OFERTA_PRODUCTO_IMAGEN_UNO, OFERTA_PRODUCTO_IMAGEN_DOS, OFERTA_PRODUCTO_IMAGEN_TRES, OFERTA_STATUS, OFERTA_CANTIDAD, OFERTA_DISPONIBLE, OFERTA_MINIMO, OFERTA_PRECIO_MINORISTA, OFERTA_PRECIO_MAYORISTA, OFERTA_USUARIO_ID, USUARIO.USUARIO_RAZON_SOCIAL, OFERTA_LOCAL_DESCRIPCION, OFERTA_DOMICILIO_RETIRO, OFERTA_HORARIO_RETIRO, OFERTA_CELULAR, OFERTA_ITEM_ID, ITEM.ITEM_DESCRIPCION, OFERTA_RUBRO_ID, RUBRO.RUBRO_DESCRIPCION, OFERTA_MARCA, OFERTA_CATEGORIA_ID, CATEGORIA.CATEGORIA_DESCRIPCION, OFERTA_FECHA_ELABORACION, OFERTA_FECHA_VENCIMIENTO FROM OFERTA LEFT OUTER JOIN EMPAQUE ON OFERTA.OFERTA_EMPAQUE_ID = EMPAQUE.EMPAQUE_ID LEFT OUTER JOIN USUARIO ON OFERTA.OFERTA_USUARIO_ID = USUARIO.USUARIO_ID LEFT OUTER JOIN ITEM ON OFERTA.OFERTA_ITEM_ID = ITEM.ITEM_ID LEFT OUTER JOIN RUBRO ON OFERTA.OFERTA_RUBRO_ID = RUBRO.RUBRO_ID LEFT OUTER JOIN CATEGORIA ON OFERTA.OFERTA_CATEGORIA_ID = CATEGORIA.CATEGORIA_ID '

}